!     REAL PRECISION DEFINITION
      MODULE PREC
!      INTEGER, PARAMETER :: P1 = SELECTED_REAL_KIND(6,37)
      INTEGER, PARAMETER :: P2 = SELECTED_REAL_KIND(15,307)
!      INTEGER, PARAMETER :: SP = SELECTED_REAL_KIND(6,37)
!      INTEGER, PARAMETER :: DP = SELECTED_REAL_KIND(15,307)
!      INTEGER, PARAMETER :: QP = SELECTED_REAL_KIND(33,4931)
      END MODULE
